### PR TITLE
feat: add support for a windows minion

### PR DESCRIPTION
**Pull request by tmeneau**
This pull request adds support for a Windows minion. Note that this support comes with one breaking set of breaking changes, a couple of caveats, and the sneaky addition of a nice bonus feature:

#### Breaking Change
The testbed configuration had to change to clearly reflect Windows vs Ubuntu configurations. This is a breaking change that will break any local `testbed.yml` configurations.

#### Windows VM Caveats
Neither of these caveats are show-stoppers, and have clear mentions added to the README as part of this PR:

1. Vagrant Salt only supports Windows minions, not Windows masters;
2. Vagrant Salt only supports stable salt releases for Windows.

#### Bonus Feature:

This change also adds the following bonus feature:

1. configuring the primarymaster's IP as each minion's master by default. Note that since the provision-generated Salt configuration is replaced by any pre-existing configurations in the host's `host-data/{{ minion_id }}` folder, this should have no derogatory consequences;
2. configuring each minion's minion_id as the minion's hostname; see the same logic as above for why this shouldn't have any negative impacts.

### CODE REVIEW

**Comment by tkent** [comment]
Interesting changes. You certainly dove in here and figured it out - nice work. However, I'm going to ask for a bit more before I accept the change.

1. Please create a `CHANGELOG.md` document, link to it in the `README.md`, briefly describe the changes there, and describe how to upgrade your testbed to the current version. This is particularly interesting because you said you made a breaking change (the `vm_defaults` re-organization).

2. The "Linux Minion" reference should be "Ubuntu Minion" just to be consistent. While saying "Linux Minion" isn't wrong, we reference Ubuntu almost everywhere else since all our stuff is tested with just Ubuntu.

3. I failed to document this, but I use `_vagrantsupport/ConfigLoaderTest.rb` to test configuration-merging ruby code works as expected. Your changes brake this test, because you probably didn't know about it. Please fix the `_vagrantsupport/ConfigLoaderTest.rb` tool, and I'll see about adding a travis-ci build test for it.

**Comment by tmeneau** [comment]
Thanks for the quick feedback! I made the changes you requested to the pull request, in addition to fixing a few issues that cropped up with this implementation. This means:

1. There is now a CHANGELOG.md with a single entry for this pull request. Note that the breaking change is really just putting a few configuration options under an `ubuntu_config` key, so not a big change.

2. All references to "Linux Minion" have been changed to "Ubuntu Minion" (this includes in the testbed config).

3. I fixed the test, and  also went ahead and added a note to the README about it with instructions for running the test.

Thanks for the interest in this! Please feel free to squash all the commits together when merging in!

**Comment by tkent** [comment]
My basic tests check out and it looks good. However, it seems you forgot to commit the CHANGELOG.md file.

**Comment by tkent** [comment]
Bringing in windows minion support to the salt testbed

**Comment by tmeneau** [comment]
Thanks for the quick merge and clear feedback!

**Pull request merged**
